### ISSUE TITLE
v1.6.0 isn't compatible with Android 12

### ISSUE THREAD

**Issue by IvanYantsevych** [DIBS-Payment-Services/Easy-Android-SDK#18] opened 2021-12-21 20:11 UTC
https://developer.android.com/about/versions/12/behavior-changes-12?authuser=1#exported

**Comment by Miss-PiA** [comment] 2022-03-08 10:21
@IvanYantsevych We have checked our Easy SDK. It is working perfectly on Android 12.
Would you please let us know are you trying Native SDK, React Native or Xamarin version.

**Comment by Martanas** [comment] 2022-05-23 09:35
@Miss-PiA Issue is with Android apps targeting Android 12.

Steps to reproduce:
Compile and Target SDK versions - 31
Gradle plugin version - 7.0.4+
MiA SDK version - 1.6.0

Upon compilation you get a compile error related to MiAActivity because it's missing the exported flag in AndroidManifest.
 
How to set it and why it's needed is state here: https://developer.android.com/about/versions/12/behavior-changes-12?authuser=1#exported

**Comment by Nets-in-app** [comment] 2022-08-12 11:19
Hi,
The above issue has been resolved in version v1.6.1
Also, v1.6.1 is up on Github.

Thanks & Regards

**Closed as completed by Nets-in-app** 2022-08-12 11:19 UTC
